---
kind: Service
apiVersion: v1
metadata:
  name: notebook-generator-service
spec:
  selector:
    app: notebook-generator
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer